//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Scs.Test.RiskTools.RulePerf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ExternalData1_R	EXRKRKSQLSVR01\ExternalData1</string>
  <string>Lists_0_3	EXRKRKSQLSVR04\Lists_0_1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataImporter_DatabaseNameMapping {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataImporter_DatabaseNameMapping"]));
            }
            set {
                this["DataImporter_DatabaseNameMapping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string DataImporter_DataDirectory {
            get {
                return ((string)(this["DataImporter_DataDirectory"]));
            }
            set {
                this["DataImporter_DataDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ExternalData1_R.dbo.ReverseIPMap</string>
  <string>ExternalData1_R.dbo.BINList</string>
  <string>ExternalData1_R.dbo.namespace</string>
  <string>ExternalData1_R.dbo.AnonymousProxy</string>
  <string>ExternalData1_R.dbo.global_message</string>
  <string>ExternalData1_R.dbo.property</string>
  <string>ExternalData1_R.dbo.property_bag</string>
  <string>ExternalData1_R.dbo.property_key</string>
  <string>Lists_0_3.dbo.list_item_data</string>
  <string>Lists_0_3.dbo.factor_code</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DataExporter_TableList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataExporter_TableList"]));
            }
            set {
                this["DataExporter_TableList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CO1MPRKSQLRPL02")]
        public string DataExporter_ServerName {
            get {
                return ((string)(this["DataExporter_ServerName"]));
            }
            set {
                this["DataExporter_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IsAzureDisabled	true</string>
  <string>EnableListAzureWrite	false</string>
  <string>AsyncOutputAction	true</string>
  <string>AsyncOutputHandler/AggregationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
  <string>AsyncOutputHandler/RiskEvaluationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AzureWriteKeysAndValues_Disable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AzureWriteKeysAndValues_Disable"]));
            }
            set {
                this["AzureWriteKeysAndValues_Disable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ReplayTool")]
        public string ReplayToolPath {
            get {
                return ((string)(this["ReplayToolPath"]));
            }
            set {
                this["ReplayToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public string ReplayToolCount {
            get {
                return ((string)(this["ReplayToolCount"]));
            }
            set {
                this["ReplayToolCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string ReplayToolTPS {
            get {
                return ((string)(this["ReplayToolTPS"]));
            }
            set {
                this["ReplayToolTPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>EXRKRKSQLSVR01\ExternalData1</string>
  <string>EXRKRKSQLSVR02\RiMEConfig</string>
  <string>EXRKRKSQLSVR02\ExternalData2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabasesToBeBackedup {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabasesToBeBackedup"]));
            }
            set {
                this["DatabasesToBeBackedup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SQLCommandTimeout {
            get {
                return ((int)(this["SQLCommandTimeout"]));
            }
            set {
                this["SQLCommandTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int SQLConnectionTimeout {
            get {
                return ((int)(this["SQLConnectionTimeout"]));
            }
            set {
                this["SQLConnectionTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IsAzureDisabled	true</string>
  <string>EnableListAzureWrite	true</string>
  <string>AsyncOutputAction	true</string>
  <string>AsyncOutputHandler/AggregationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
  <string>AsyncOutputHandler/RiskEvaluationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AzureWriteKeysAndValues_Enable {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AzureWriteKeysAndValues_Enable"]));
            }
            set {
                this["AzureWriteKeysAndValues_Enable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RiskAPICaller_IsZipped {
            get {
                return ((bool)(this["RiskAPICaller_IsZipped"]));
            }
            set {
                this["RiskAPICaller_IsZipped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float RiskAPICaller_TPS {
            get {
                return ((float)(this["RiskAPICaller_TPS"]));
            }
            set {
                this["RiskAPICaller_TPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\RulePerf\\ReplayData.dat.gz")]
        public string RiskAPICaller_DataFilePath {
            get {
                return ((string)(this["RiskAPICaller_DataFilePath"]));
            }
            set {
                this["RiskAPICaller_DataFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int RiskAPICaller_Count {
            get {
                return ((int)(this["RiskAPICaller_Count"]));
            }
            set {
                this["RiskAPICaller_Count"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RiskAPICaller_NewGuid {
            get {
                return ((bool)(this["RiskAPICaller_NewGuid"]));
            }
            set {
                this["RiskAPICaller_NewGuid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RiskAPICaller_NeedLog {
            get {
                return ((bool)(this["RiskAPICaller_NeedLog"]));
            }
            set {
                this["RiskAPICaller_NeedLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Rule Perf Testing\"")]
        public string RiskAPICaller_Description {
            get {
                return ((string)(this["RiskAPICaller_Description"]));
            }
            set {
                this["RiskAPICaller_Description"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public float RiskAPICaller_JumpMinute {
            get {
                return ((float)(this["RiskAPICaller_JumpMinute"]));
            }
            set {
                this["RiskAPICaller_JumpMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\transfer\\transfer\\v-jetian")]
        public string TransferFolder {
            get {
                return ((string)(this["TransferFolder"]));
            }
            set {
                this["TransferFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian")]
        public string BedTransferFolder {
            get {
                return ((string)(this["BedTransferFolder"]));
            }
            set {
                this["BedTransferFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\ruleperf\\RiskConfigAutoPropTool.exe -ImportMachine:EXRKRKU" +
            "TLBEP01 -ImportPath:C:\\RulePerf\\RiMEConfig.xml")]
        public string SyncSettingsCommand {
            get {
                return ((string)(this["SyncSettingsCommand"]));
            }
            set {
                this["SyncSettingsCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian\\EXRK.xml")]
        public string ServerAssignmentFilePath {
            get {
                return ((string)(this["ServerAssignmentFilePath"]));
            }
            set {
                this["ServerAssignmentFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string RiskAPICaller_RuleID {
            get {
                return ((string)(this["RiskAPICaller_RuleID"]));
            }
            set {
                this["RiskAPICaller_RuleID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RiskAPICaller_NeedReport {
            get {
                return ((bool)(this["RiskAPICaller_NeedReport"]));
            }
            set {
                this["RiskAPICaller_NeedReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXRKPSSQLTAK01")]
        public string RiskAPICaller_TakoServer {
            get {
                return ((string)(this["RiskAPICaller_TakoServer"]));
            }
            set {
                this["RiskAPICaller_TakoServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\transfer\\transfer\\v-jetian")]
        public string CopyDataFiles_From {
            get {
                return ((string)(this["CopyDataFiles_From"]));
            }
            set {
                this["CopyDataFiles_From"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian")]
        public string CopyDataFiles_To {
            get {
                return ((string)(this["CopyDataFiles_To"]));
            }
            set {
                this["CopyDataFiles_To"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyDataFiles_DeleteSource {
            get {
                return ((bool)(this["CopyDataFiles_DeleteSource"]));
            }
            set {
                this["CopyDataFiles_DeleteSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>IsAzureDisabled	true</string>
  <string>EnableListAzureWrite	true</string>
  <string>AsyncOutputAction	true</string>
  <string>AsyncOutputHandler/AggregationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
  <string>AsyncOutputHandler/RiskEvaluationOutputHandler	{""Parameters"":[],""Weight"":65536}</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GlobalSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GlobalSettings"]));
            }
            set {
                this["GlobalSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bcp.exe")]
        public string DataImporter_BCP_Path {
            get {
                return ((string)(this["DataImporter_BCP_Path"]));
            }
            set {
                this["DataImporter_BCP_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection ChangeGroupXmlFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChangeGroupXmlFiles"]));
            }
            set {
                this["ChangeGroupXmlFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bed")]
        public string Environment {
            get {
                return ((string)(this["Environment"]));
            }
            set {
                this["Environment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian\\TestScripts.txt")]
        public string ScriptsPath {
            get {
                return ((string)(this["ScriptsPath"]));
            }
            set {
                this["ScriptsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\transfer\\transfer\\RulePerf\\MergedChangeGroupHistory.xml")]
        public string ChangeGroupMergeHistoryFilePath {
            get {
                return ((string)(this["ChangeGroupMergeHistoryFilePath"]));
            }
            set {
                this["ChangeGroupMergeHistoryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v-jetian")]
        public string DomainUserName {
            get {
                return ((string)(this["DomainUserName"]));
            }
            set {
                this["DomainUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DomainPassword {
            get {
                return ((string)(this["DomainPassword"]));
            }
            set {
                this["DomainPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FAREAST")]
        public string Domain {
            get {
                return ((string)(this["Domain"]));
            }
            set {
                this["Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>EXRKPGSQLAPP02</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RestartMachineList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RestartMachineList"]));
            }
            set {
                this["RestartMachineList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2:00:00")]
        public string RestartMachineTimeoutTimeSpan {
            get {
                return ((string)(this["RestartMachineTimeoutTimeSpan"]));
            }
            set {
                this["RestartMachineTimeoutTimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0:02:00")]
        public string RestartMachinePollInterval {
            get {
                return ((string)(this["RestartMachinePollInterval"]));
            }
            set {
                this["RestartMachinePollInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection BackedUpDatabasesWhenApplyingChanges {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BackedUpDatabasesWhenApplyingChanges"]));
            }
            set {
                this["BackedUpDatabasesWhenApplyingChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeployTargetPath {
            get {
                return ((string)(this["DeployTargetPath"]));
            }
            set {
                this["DeployTargetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteMachine {
            get {
                return ((string)(this["RemoteMachine"]));
            }
            set {
                this["RemoteMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemoteCommand {
            get {
                return ((string)(this["RemoteCommand"]));
            }
            set {
                this["RemoteCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string RemoteUserName {
            get {
                return ((string)(this["RemoteUserName"]));
            }
            set {
                this["RemoteUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Bugsfor$")]
        public string RemotePassword {
            get {
                return ((string)(this["RemotePassword"]));
            }
            set {
                this["RemotePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string RemoteDomain {
            get {
                return ((string)(this["RemoteDomain"]));
            }
            set {
                this["RemoteDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jeff")]
        public string TestSetting {
            get {
                return ((string)(this["TestSetting"]));
            }
            set {
                this["TestSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InitialStepFilePath {
            get {
                return ((string)(this["InitialStepFilePath"]));
            }
            set {
                this["InitialStepFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResultLogPath {
            get {
                return ((string)(this["ResultLogPath"]));
            }
            set {
                this["ResultLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public string RemoteTimeout {
            get {
                return ((string)(this["RemoteTimeout"]));
            }
            set {
                this["RemoteTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#tps#")]
        public string RiskAPICaller_TPS_BaseLine {
            get {
                return ((string)(this["RiskAPICaller_TPS_BaseLine"]));
            }
            set {
                this["RiskAPICaller_TPS_BaseLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#tps#")]
        public string RiskAPICaller_TPS_ChangedRun {
            get {
                return ((string)(this["RiskAPICaller_TPS_ChangedRun"]));
            }
            set {
                this["RiskAPICaller_TPS_ChangedRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public string RiskAPICaller_Count_Run {
            get {
                return ((string)(this["RiskAPICaller_Count_Run"]));
            }
            set {
                this["RiskAPICaller_Count_Run"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>v-jetian@microsoft.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EmailToList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailToList"]));
            }
            set {
                this["EmailToList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>v-jetian@microsoft.com</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EmailCCList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EmailCCList"]));
            }
            set {
                this["EmailCCList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailUserName {
            get {
                return ((string)(this["EmailUserName"]));
            }
            set {
                this["EmailUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
            set {
                this["EmailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1705</string>\r\n  <string>1706</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RuleIds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RuleIds"]));
            }
            set {
                this["RuleIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int DownloadResponseTimeoutMilliseconds {
            get {
                return ((int)(this["DownloadResponseTimeoutMilliseconds"]));
            }
            set {
                this["DownloadResponseTimeoutMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-----------------------------7dc1092810278
Content-Disposition: form-data; name=""__RequestVerificationToken""

mi5qZ5l8M16EB6ZARIibqIycc9N/K4T65cRehGGCe42waCS5hE+Y55DsIezDzwoTz8qIJ9Qrv8JytcEMC3sMfpkozpPb9qhcMqxwa9R5PQWevx4ea9UIl57B4HFvij+PAeTCSyjjM/UpfdlVgIYxMAPvF73pcOu6pU8AXQc1lH0SZ5T388Zy1xaUhOd/Rnl4
-----------------------------7dc1092810278
Content-Disposition: form-data; name=""ChangeGroup.GroupId""

6e7c0c28-2c43-431f-8681-dd9e386d1aa0
-----------------------------7dc1092810278
Content-Disposition: form-data; name=""ChangeGroup.Description""

bug#54037[Risk][Rule Change] Type 2 change group: Add Async Low Risk check For Partner spsp_xbox and cm_windows
-----------------------------7dc28b1d616dc
Content-Disposition: form-data; name=""ChangeGroup.Comments""

[Risk][Rule Change] Type 2 change group: Add Async Low Risk check For Partner spsp_xbox and cm_windows
-----------------------------7dc1092810278
Content-Disposition: form-data; name=""importedXmlFileInput""; filename=""""
Content-Type: application/octet-stream


-----------------------------7dc1092810278
Content-Disposition: form-data; name=""submitButton""

Export change group xml
-----------------------------7dc1092810278--")]
        public string RCMInputToken {
            get {
                return ((string)(this["RCMInputToken"]));
            }
            set {
                this["RCMInputToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://ctpcmco1/RCM/ChangeGroup/Save?groupId=65b3be47-b9cf-4f39-8083-22dfeb5002cc</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ChangeGroupLinks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChangeGroupLinks"]));
            }
            set {
                this["ChangeGroupLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\transfer\\transfer\\RulePerf\\RuleSrcFiles")]
        public string RuleSourceFolder {
            get {
                return ((string)(this["RuleSourceFolder"]));
            }
            set {
                this["RuleSourceFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian")]
        public string RuleDestFolder {
            get {
                return ((string)(this["RuleDestFolder"]));
            }
            set {
                this["RuleDestFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\ruleperf\\RiskConfigAutoPropTool.exe -ExportMachine:CTPCMCO" +
            "1 -ExportPath:\\\\bedtransfer\\transfer\\v-jetian\\RiMEConfig.xml")]
        public string DownloadRiMEConfigCommand {
            get {
                return ((string)(this["DownloadRiMEConfigCommand"]));
            }
            set {
                this["DownloadRiMEConfigCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\bedtransfer\\transfer\\RulePerf\\RiskConfigImportExport.dll</string>\r\n</Arr" +
            "ayOfString>")]
        public global::System.Collections.Specialized.StringCollection DownloadRiMEConfigReferencedList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DownloadRiMEConfigReferencedList"]));
            }
            set {
                this["DownloadRiMEConfigReferencedList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>RiskEmailSender.dll</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DeployReferencedList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeployReferencedList"]));
            }
            set {
                this["DeployReferencedList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\ruleperf\\RiskConfigAutoPropTool.exe -ImportMachine:EXRKRKU" +
            "TLBEP01 -ImportPath:C:\\RulePerf\\{0} -UseNewGroupID:True")]
        public string ApplyChangeGroupCommand {
            get {
                return ((string)(this["ApplyChangeGroupCommand"]));
            }
            set {
                this["ApplyChangeGroupCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string RiskAPICaller_ImpersonateUserName {
            get {
                return ((string)(this["RiskAPICaller_ImpersonateUserName"]));
            }
            set {
                this["RiskAPICaller_ImpersonateUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXRK")]
        public string RiskAPICaller_ImpersonateDomain {
            get {
                return ((string)(this["RiskAPICaller_ImpersonateDomain"]));
            }
            set {
                this["RiskAPICaller_ImpersonateDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Bugsfor$")]
        public string RiskAPICaller_ImpersonatePassword {
            get {
                return ((string)(this["RiskAPICaller_ImpersonatePassword"]));
            }
            set {
                this["RiskAPICaller_ImpersonatePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>iisreset</string>\r\n  <string>cmd /c echo Hello</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Commands {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Commands"]));
            }
            set {
                this["Commands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportServer,SQLSERVERAGENT,MSSQLSERVER")]
        public string ServicesToRestart {
            get {
                return ((string)(this["ServicesToRestart"]));
            }
            set {
                this["ServicesToRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RestartServicesTargetMachine {
            get {
                return ((string)(this["RestartServicesTargetMachine"]));
            }
            set {
                this["RestartServicesTargetMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RestartServicesUserName {
            get {
                return ((string)(this["RestartServicesUserName"]));
            }
            set {
                this["RestartServicesUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RestartServicesDomain {
            get {
                return ((string)(this["RestartServicesDomain"]));
            }
            set {
                this["RestartServicesDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RestartServicesPassword {
            get {
                return ((string)(this["RestartServicesPassword"]));
            }
            set {
                this["RestartServicesPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Administrator")]
        public string CommandsUserName {
            get {
                return ((string)(this["CommandsUserName"]));
            }
            set {
                this["CommandsUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#Bugsfor$")]
        public string CommandsPassword {
            get {
                return ((string)(this["CommandsPassword"]));
            }
            set {
                this["CommandsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXRK")]
        public string CommandsDomain {
            get {
                return ((string)(this["CommandsDomain"]));
            }
            set {
                this["CommandsDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeployUserName {
            get {
                return ((string)(this["DeployUserName"]));
            }
            set {
                this["DeployUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeployPassword {
            get {
                return ((string)(this["DeployPassword"]));
            }
            set {
                this["DeployPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeployDomain {
            get {
                return ((string)(this["DeployDomain"]));
            }
            set {
                this["DeployDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int TransactionCountPerRule {
            get {
                return ((int)(this["TransactionCountPerRule"]));
            }
            set {
                this["TransactionCountPerRule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\bedtransfer\\transfer\\v-jetian\\")]
        public string ChangeGroupDownloadTo {
            get {
                return ((string)(this["ChangeGroupDownloadTo"]));
            }
            set {
                this["ChangeGroupDownloadTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>\\\\bedtransfer\\transfer\\RulePerf\\Common.dll</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ChangeGroupDownloadingReferencedList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ChangeGroupDownloadingReferencedList"]));
            }
            set {
                this["ChangeGroupDownloadingReferencedList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DataImporter_IsContinueRun {
            get {
                return ((bool)(this["DataImporter_IsContinueRun"]));
            }
            set {
                this["DataImporter_IsContinueRun"] = value;
            }
        }
    }
}
